name: 'Run pyflakes with reviewdog'
description: '🐶 Run pyflakes with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa, IK'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'chevron-down'
  color: 'green'
